steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 1. Inject the variables into app.yaml
        sed -i "s|PROJECT_ID_PLACEHOLDER|${_PROJECT_ID}|g" app.yaml
        sed -i "s|DATASET_PLACEHOLDER|${_BIGQUERY_DATASET}|g" app.yaml
        
        # 2. Deploy (without the invalid flag)
        gcloud app deploy app.yaml \
          --project=${_PROJECT_ID} \
          --quiet

    dir: 'visualization'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY